services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema_api
    restart: always
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
      
      - DB_HOST=postgres_db 
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=cinema_db
      
      
    depends_on:
      - postgres_db
    networks:
      - cinema-network

  postgres_db:
    image: postgres:15-alpine
    container_name: cinema_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cinema-network

  redis:
    image: redis:alpine
    container_name: cinema_redis
    ports:
      - "6379:6379"
    networks:
      - cinema-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cinema_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge

volumes:
  pgdata: