services:
  api:
    build: . 
    container_name: cinema-api
    ports:
      - "3000:3000" 
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin123
      - DB_DATABASE=cinema_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URI=amqp://user:password@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
  postgres:
    image: postgres:14-alpine
    container_name: cinema-postgres
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=cinema_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: cinema-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management #
    container_name: cinema-rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
volumes:
  pgdata: